### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by flaneuse** [tessam30/Bangladesh#14]
### Must do
- [ ] Medical expenses shocks
  - [x] Regressions --> @tessam30 
  - [ ] Spatial interpolations --> @pgault 
  - [ ] GWRs --> @jfconley @bmccusker 
  - [ ] LISAs/hotspot analysis  @jfconley @bmccusker
  - [ ] plots --> @flaneuse
    - [x] point estimates by region.
    - [ ] OLS marginal effects
    - [ ] When shocks happened
    - [ ] How severe were shocks
    - [ ] How people cope
- [x] Ag shocks
  - [ ] Regressions --> @tessam30 
  - [ ] Spatial interpolations --> @pgault 
  - [ ] GWRs -->  @jfconley @bmccusker
  - [ ] LISAs/hotspot analysis  @jfconley @bmccusker
  - [ ] plots --> @flaneuse
    - [x] point estimates by region.
    - [ ] OLS marginal effects
    - [ ] When shocks happened
    - [ ] How severe were shocks
    - [ ] How people cope
- [x] Price shocks
  *_Note: GWRs probably meaningless b/c price shocks highly localized. *_
  - [ ] Regressions --> @tessam30 
  - [ ] Interpolations --> @pgault 
  - [ ] plots --> @flaneuse
    - [x] point estimates by region.
    - [ ] OLS marginal effects
    - [ ] When shocks happened
    - [ ] How severe were shocks
    - [ ] How people cope
- [x] Hazard shocks
  *_Note: GWRs probably meaningless b/c price shocks highly localized. *_
  - [ ] Regressions --> @tessam30 
  - [ ] Interpolations --> @pgault 
  - [ ] plots --> @flaneuse
    - [x] point estimates by region.
    - [ ] OLS marginal effects
    - [ ] When shocks happened
    - [ ] How severe were shocks
    - [ ] How people cope
- [x] Nutrition
  - [ ] Regressions x 3(?): stunting, wasting, underwgt  --> @tessam30 
  - [ ] choropleths x 6: --> @flaneuse
  - [ ] stunting, wasting, underwgt by age --> flaneuse
  - [ ] Dietary diversity Maps & graphics --> @pgault  @flaneuse 
- [x] FtF baseline equivs
- [x] Basemaps @pgault 
### It'd be nice if...
- [ ] Access to health services
- [x] FCS or DD?
- [x] Food security
- [x] Child nutrition, breast feeding, food aid to lactating women.

**Comment by tessam30** [comment]
> FCS or DD?
This is all calculated and just needs to be mapped and visualized.

**Comment by dwahid** [comment]
FCS?orDD? ???? Can you plz clear this more?


Sent from Samsung Mobile

Tim Essam <notifications@github.com> wrote:

FCS or DD?
This is all calculated and just needs to be mapped and visualized.
